# Generated by Django 2.1.1 on 2019-04-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
